
version: '3'
services:
  app:
    container_name: docker-mongo-demo1
    restart: always
    build: .
    ports:
    - '5500:5500'
    external_links:
    - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - '27012:27017'
            